// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "fhevm-contracts/contracts/token/ERC20/ConfidentialERC20Wrapped.sol";

/**
 * @title  MockcUSDT
 * @notice Confidential USDT — wraps MockUSDT into an encrypted ERC-20 (ERC-7984).
 *
 *         Wrap flow:
 *           1. Investor holds MockUSDT (plaintext).
 *           2. investor.approve(mockCUSDT, amount)
 *           3. investor.wrap(amount)  → plaintext balance zeroed, euint64 balance credited.
 *           4. Investor uses encrypted balance in Subscription.subscribe().
 *
 *         Name/symbol are auto-generated by ConfidentialERC20Wrapped:
 *           "Mock USDT" → "Confidential Mock USDT"
 *           "mUSDT"     → "mUSDTc"
 *
 *         To upgrade to canonical cUSDT: set CUSDT_ADDRESS in .env and point
 *         Subscription.sol at the canonical address — no other changes needed.
 */
contract MockcUSDT is ConfidentialERC20Wrapped {
    /**
     * @param mockUSDT_          Address of MockUSDT (or canonical USDT for production).
     * @param maxDecryptionDelay Maximum seconds for the gateway decryption callback (≤ 1 day).
     */
    constructor(address mockUSDT_, uint256 maxDecryptionDelay)
        ConfidentialERC20Wrapped(mockUSDT_, maxDecryptionDelay)
    {}
}
